version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - .env

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: \${VOLUME_PATH}/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: \${VOLUME_PATH}/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge
